# Funding options for Frutisoft
# This is a personal passion project - sponsorships not currently enabled
# GitHub will display this in the repository's "Sponsor" button area

# Uncomment and configure when ready:
# github: [username]
# patreon: username
# ko_fi: username
