# Pull Request Labeler Configuration
# Automatically labels PRs based on changed files

'component: compiler':
  - changed-files:
    - any-glob-to-any-file: 'packages/fruti-compiler/**/*'

'component: kernel':
  - changed-files:
    - any-glob-to-any-file: 'packages/aero-kernel/**/*'

'component: language':
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/fruti/language/**/*'
      - 'docs/fruti/Language-Design-Decisions.md'

'component: stdlib':
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/fruti/language/Reference/Standard-Library.md'
      - 'packages/fruti-compiler/src/stdlib/**/*'

'component: tooling':
  - changed-files:
    - any-glob-to-any-file: 'tools/**/*'

'component: ci-cd':
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/dependabot.yml'

'type: documentation':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'
      - 'website/**/*'

'type: test':
  - changed-files:
    - any-glob-to-any-file:
      - '**/tests/**/*'
      - '**/*_test.rs'
      - '**/*_tests.rs'

'type: refactor':
  - changed-files:
    - any-glob-to-any-file: 'packages/fruti-compiler/src/**/*.rs'
    - all-globs-to-all-files: '!**/tests/**/*'

'dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/dependabot.yml'